# branchLabels:
#   dev: ['dev']
#   main: ['Main']
#   bugFix:  ['bugFix']
#   crashFix:  ['crashFix']
#   hotFix:  ['hotFix']
#   feature:  ['feature']
#   enhancement:  ['enhancement']
#   documentation:  ['documentation']
